### ISSUE TITLE
Show most recent review stats.

### ISSUE THREAD

**Issue by v0dro** [dennmart/wanikani-gem#1]
The API also has support for reviews: https://docs.api.wanikani.com/20170710/#reviews

Would be great to have that in the gem too.

**Comment by dennmart** [comment]
The latest version of the gem that was released just now has support for this!

```ruby
require 'wanikani'

Wanikani.configure do |config|
  config.api_key = "YOUR_API_KEY"
end

# Returns all reviews.
Wanikani::Review.find_all

# Find specific reviews using different parameters
Wanikani::Review.find_by(subject_ids: 6585)

# Find a single review by ID
Wanikani::Review.find(7893127)
```

I'll include more detailed examples of these API calls in the README or separate documentation in the near future.
